database:
  domain: localhost
  port: 3306
  username: root
  password: 123456
  databaseName: wedding_dress_manage

file:
  path: /Users/yanglei/Desktop/WeddingImg/
  randNumLen: 4
  imgType: ["jpg", "png", "jpeg"]